### PR TITLE
Add pub method to call sync_styles on current entity's text

### PR DESCRIPTION
**Pull request by rhelmot**
This is necessary if you want to have a custom draw method that uses the text draw stuff, lol

### CODE REVIEW

**Comment by geom3trik** [comment]
Is this not an implementation detail though? Should we not expose some method to render text ina custom draw and call this internally? Or I guess is it not so simple because you need entities for the buffers?

**Comment by rhelmot** [comment]
uhhhhhhhhh I suppose this could be done automatically before drawing but we would need to somehow cache and then invalidate the synced status. not sure how to do that.

**Comment by geom3trik** [comment]
hmmm right. I'm happy to merge this solution for now and we can come back to it if we can think of a beter solution later. Do you have an example of a custom draw function with text for how to use this? Presumably you just call it before calling `draw_text`?

**Comment by rhelmot** [comment]
Yes - you need to call it before calling any of draw_text, draw_highlight, or draw_caret, and the results are valid until the text or any of its properties are updated. My main reason for not wanting to do a cache yet upon some further reasoning is that this will interact weirdly with text spans, and I would rather fast-track spans.

**Pull request merged**
