### PR TITLE
Optimize draw call in view trait

### PR DESCRIPTION
**Pull request by KDecay**
The diff looks a bit wild, but I just moved the content of the `draw` function of the `View` trait into a separate function called `draw_view`. This reduces the binary size quite a bit.

# Comparison

### Dropdown Example

Old: 13752 kb
New: 13484 kb

### Crud Example

Old: 13936 kb
New: 13608 kb

### Dropdown Example

Old: 8784 kb
New: 8696 kb

### Crud Example

Old: 8972 kb
New: 8832 kb

### CODE REVIEW

**Comment by robbert-vdh** [comment]
Did you try comparing compile times with and without this change, particularly for slightly less trivial applications? By moving the drawing code to a function like this significantly less code needs to be generated, so I can imagine that optimizing may also become faster.

**Review by geom3trik — APPROVED** [review]

**Comment by KDecay** [comment]
> Have you tried comparing compile times with and without this change, particularly for slightly less trivial applications? By moving the drawing code to a function like this significantly less code needs to be generated, so I can imagine that optimizing may also become faster.

@robbert-vdh I haven't yet but I'll put that on my todo list and let you know the results! I'm certain that it has a positive effect on compile time as well.

**Comment by KDecay** [comment]
@robbert-vdh @geom3trik I just tested the compile time difference this change made and it's pretty huge. I made a simple crate that just defines 100 types and implements the default `View` implementation (`impl View for Foo {}`). I compiled it using `cargo build --timings` and checked the time it took the crate to build (just the crate not `Vizia`).

The results are as follows:
- Before: 6.95s
- After: 4.27s

Of course this is not a scientific result by any means but it should show how much impact this change had.

**Comment by robbert-vdh** [comment]
I'm also curious about the binary size difference between the two (if you just add all those 100 views in an application so they don't get optimized out).

**Comment by KDecay** [comment]
Alright I tested it again now using 1000 Types. All of the builds use `winit` and are build using the following commands:
- Release: `cargo build --release --timings`
- Debug: `cargo build --timings`

# Debug builds

## Before 

Time: 36.88s
Size: 237MB

## After

Time: 8.8s
Size: 169MB

# Release builds

## Before 

Time: 211.86s
Size: 27MB

## After

Time: 13.67s
Size: 11MB

**Comment by geom3trik** [comment]
Wow, these time differences are insane! Is this a clean build both times? I.e. no incremental builds?

**Comment by KDecay** [comment]
@geom3trik Yup I always ran `cargo clean` before every test.

**Pull request merged**
