### PR TITLE
Baseview mouse event fix

### PR DESCRIPTION
**Pull request by ejjonny**
Possible fix for #422 

Prevents this sequence of events:

1. Frame update calls layout system
2. Baseview sends mousemove & layout system sends a mousemove
3. Frame update processes baseview mousemove, & then processes layout mousemove overwriting the real cursor position
4. Frame update then calls layout which re-sends the stale cursor value for the next frame update
5. Repeat from 3 for the duration of the gesture triggering relayout, or until relayout is not performed on a frame

An alternative fix may be to prevent such frequent layout, or to investigate what is different in winit feature that prevents this, but I think the mousemoved event that was being sent here was sort of a band-aid in the first place?

### CODE REVIEW

**Comment by geom3trik** [comment]
It's not a band-aid as such because it happens for a specific reason. A mouse move event triggers the hover system to determine which view is under the mouse. This has to be done after layout (if required). So its mouse move -> layout -> hover. However, if hovering a view causes it to move, the layout system needs to be called again and the hover system should be called again to determine what view is now under the mouse. The easiest way to do this is to push another mouse move event into the stack.

I'm not sure what the exact issue is right now, but something we did for the winit backend and possibly not the baseview one is to debounce the raw mouse move events. So if we get multiple mouse move events before an events cleared we just take the last one.

**Comment by ejjonny** [comment]
Oh yeah, I see now, winit has some state in the event loop to track whether we've moved the mouse already in a given iteration of the event loop.
Maybe it would still be useful to define an event specifically for this purpose rather than overloading mouse move events, but I don't know the repercussions well enough to be sure! 
I imagine the distinction between 'the mouse moved' & 'my view moved under the mouse' could be useful to someone implementing a view, or it could just be a pain to respond to both.

**Comment by geom3trik** [comment]
Yeh we could have another event for it I guess but the end result is the same. I.e. run the layout and hover systems again within the same loop.

I think the problem here is that baseview doesn't have a `MainEventsCleared` equivalent. The mouse move debounce was put in because a high rate mouse would cause multiple mouse move events per one main events cleared. I suspect the baseview backend will just fire the events function for every mouse move. 

I'll take a proper look at your PR soon but I think you're right that it's conflicting mouse positions from different sources within the same frame.

**Comment by geom3trik** [comment]
I'm not sure about introducing a new event just for this, but I assume this works because it's not overriding the mouse position in context and instead using what's already been set by the mouse move event?

**Comment by ejjonny** [comment]
Yeah. I looked a bit more today, the reason the knob moves wildly is because it renders based on mouse movement delta across frames. Since the stale mouse position continues to publish between real mouse move events the knob component processes a delta that doesn't exist & moves backwards or jumps around.

With some logging you can see the 307.3... position strung along over time.

```
[crates/vizia_core/src/events/event_manager.rs:191] context.mouse.cursory = 307.34766
[crates/vizia_core/src/events/event_manager.rs:191] context.mouse.cursory = 309.16016
[crates/vizia_core/src/events/event_manager.rs:191] context.mouse.cursory = 307.34766
[crates/vizia_core/src/events/event_manager.rs:191] context.mouse.cursory = 309.8203
[crates/vizia_core/src/events/event_manager.rs:191] context.mouse.cursory = 307.34766
[crates/vizia_core/src/events/event_manager.rs:191] context.mouse.cursory = 310.22656
[crates/vizia_core/src/events/event_manager.rs:191] context.mouse.cursory = 310.6211
[crates/vizia_core/src/events/event_manager.rs:191] context.mouse.cursory = 307.34766
[crates/vizia_core/src/events/event_manager.rs:191] context.mouse.cursory = 311.01953
```

**Comment by geom3trik** [comment]
Is there a way to fix this without introducing a new window event?

**Comment by ejjonny** [comment]
The best alternative I can think of would be to add some 'needs_hover' state somewhere appropriate.

Hover ultimately depends on layout, but layout happens after events are processed, so you could set `needs_hover = true` while processing events & then call the hover system once layout is ready.
This should make the mousemove event published during layout unnecessary.

This way nothing is delayed to the next frame, no events are overloaded, and no new events are introduced.

This is assuming layout doesn't directly or indirectly depend on hover being finished, I'm not sure whether that's the case.

If this sounds reasonable, I'd like your thoughts on the best place for the needs_hover state.

**Comment by geom3trik** [comment]
> The best alternative I can think of would be to add some 'needs_hover' state somewhere appropriate.
> 
> Hover ultimately depends on layout, but layout happens after events are processed, so you could set `needs_hover = true` while processing events & then call the hover system once layout is ready.
> This should make the mousemove event published during layout unnecessary.
> 
> This way nothing is delayed to the next frame, no events are overloaded, and no new events are introduced.
> 
> This is assuming layout doesn't directly or indirectly depend on hover being finished, I'm not sure whether that's the case.
> 
> If this sounds reasonable, I'd like your thoughts on the best place for the needs_hover state.

The issue isn't really that the hover system needs to happen after layout, the extra event was necessary to wake up the event loop and trigger another run of the hover system. For example:

1. User moves the mouse over a view
2. Hover system is run (I'm assuming layout has already happened previously).
3. Style system runs and determines that the view should be hidden/moved when hovered.
4. Layout runs and moves the view. The mouse is now hovering over the view underneath the one that moved.
5. The event loop waits for an event but a moving view doesn't trigger one (well it technically emits a geometry changed event)
6. Push a manual mouse move event to wake the event loop and trigger the hover system to run.
7. Hover system determines the view underneath is the one actually being hovered.

**Pull request closed without merging**
